name: Run Python Tests
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with unitests
        run: |
          pip install coverage
          coverage run -m unittest tests/test_number.py
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: 1eba1671-1ebc-42e7-a3d5-1b4cc34890b4
          fail_ci_if_error: true
